name: Deploy to Clojars

on:
  push:
  #release:
  #  types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: latest
          
      - name: Install git credentials
        run: git config --global user.name "github-actions" && git config --global user.email "actions@github.com"

      - name: Build JAR with depstar
        run: clojure -X:jar

      - name: Deploy to Clojars
        uses: clojars/action@v1
        with:
          group-id: io.github.rafaelcampo  
          artifact-id: dynamodb-migrate           
          version: 0.1.0-beta #_${{ github.ref_name }}   
          jar: target/dynamodb-migrate.jar         # path to your jar
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_TOKEN: ${{ secrets.CLOJARS_TOKEN }}